package com.zander;
import java.util.Scanner;
import java.util.Random;

class Guess_Number{
    private int user_input;
    //getters & setters of User_Input
    public int getUser_input() {
        return user_input;
    }

    public void setUser_input(int user_input) {
        this.user_input = user_input;
    }

    //getters & setters of Comp_Input
    private int comp_input;

    public int getComp_input() {
        return comp_input;
    }

    public void setComp_input(int comp_input) {
        this.comp_input = comp_input;
    }

    int GuessTime = 0;
    //Using Constructor To Set the Value of random number generated by computer

    public Guess_Number(){
    Random r = new Random();
    this.setComp_input(r.nextInt(10));
    }

    void UserInput(){
    Scanner sc = new Scanner(System.in);
    System.out.print("Enter a number within 10: ");
    user_input = sc.nextInt();
    if(user_input>10){
        System.out.println("Invalid Input! Try again");
        UserInput();
    }
    }

    //Checking If The Guessed Value is correct or not
    boolean CorrectGuess() {
         GuessTime++;
         if (user_input == comp_input){
            System.out.println("You Guessed The Correct number!");
            System.out.println("Your Score is: " + GuessTime);
             return true;
        }
        else if (user_input > comp_input){
            System.out.println("The Guessed number is Greater than the actual number, Try again");
            return false;
        }
        else {
            System.out.println("The Guessed number is Less than the actual number, Try again");
            return false;
        }
    }
}

public class Guess_Number_Game {
    public static void main(String[] args) {
        Guess_Number obj = new Guess_Number();
        boolean a = false;
        while (!a) {
            obj.UserInput();
            a = obj.CorrectGuess();
        }
    }
}
